spring:
  application:
    name: application

  datasource:
    url: jdbc:postgresql://localhost:5432/turismo_db
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver

    logging:
      level:
        org.springframework.security: DEBUG


  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

api:
  base-path: /api/v1
  endpoints:
    login: /login
    tipo-documento: /tipo-documento

springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    url: /openapi/api-docs.yml
  api-docs:
    enabled: true
    resolve-schema-properties: true