spring:
  application:
    name: application

  datasource:
    url: jdbc:postgresql://localhost:5432/turismo_db
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver

    logging:
      level:
        org.springframework.security: DEBUG


  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

api:
  base-path: /api/v1
  endpoints:
    login: /login

openapi:
  title: Turismo Show API
  version: 1.0.0
  description: Documentacion de la API de Turismo en Ciclas
  terms: http://swagger.io/terms/

  license:
    name: Apache 2.0
    url: http://springdoc.org

  security:
    name: bearerAuth
    scheme: bearer
    format: JWT
